# -*- coding: utf-8 -*-
"""MODI_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WfAbpn-wpaqwwB-Mswhi2SOVfzpgrT8
"""

# Commented out IPython magic to ensure Python compatibility.
# ============================================
# 第 1 步：环境准备
# ============================================
print("="*70)
print("  🚀 ClimaHealth AI")
print("="*70)

# 上传项目压缩包
from google.colab import files
print("\n climahealth-ai.zip 文件")
uploaded = files.upload()

# 解压
!unzip -q climahealth-ai.zip
# %cd climahealth-ai/backend

# 安装依赖
!pip install -q requests pandas scikit-learn joblib matplotlib seaborn

print("\✅")

# ============================================
# 第 2 步：创建融合模块文件 - Part 1
# ============================================
print("\n" + "="*70)
print("  📝 创建疾病领域特征工程模块")
print("="*70)

disease_features_code = "disease_domain_features.py"
"""
融合 DL_climate 的领域建模 + ClimaHealth AI 的通用框架
为每种疾病定制特征工程，基于流行病学原理
"""

import numpy as np
import pandas as pd
from abc import ABC, abstractmethod

class DiseaseFeatureEngineer(ABC):
    """疾病特征工程基类"""

    @abstractmethod
    def compute_transmission_factor(self, climate_df: pd.DataFrame) -> np.ndarray:
        pass

    @abstractmethod
    def get_optimal_climate_range(self) -> dict:
        pass


class MalariaFeatures(DiseaseFeatureEngineer):
    """疟疾特异性特征（融合 DL_climate 的高斯响应曲线）"""

    def compute_transmission_factor(self, climate_df: pd.DataFrame) -> np.ndarray:
        temp = climate_df['temperature'].values
        precip = climate_df['precipitation'].values
        humidity = climate_df.get('humidity', pd.Series([75]*len(temp))).values

        # 温度响应：高斯曲线（20-30°C最适宜）
        temp_factor = np.exp(-0.5 * ((temp - 25) / 5) ** 2)

        # 降水响应
        precip_factor = np.where(
            precip < 200,
            1 + 0.003 * precip,
            1 + 0.003 * 200 - 0.002 * (precip - 200)
        )
        precip_factor = np.clip(precip_factor, 0.5, 2.0)

        # 湿度响应
        humidity_factor = np.where(humidity > 60, 0.5 + 0.01 * humidity, 0.8)

        return temp_factor * precip_factor * humidity_factor

    def get_optimal_climate_range(self) -> dict:
        return {
            'temperature': (20, 32),
            'precipitation': (50, 300),
            'humidity': (60, 90),
        }


class DengueFeatures(DiseaseFeatureEngineer):
    """登革热特异性特征"""

    def compute_transmission_factor(self, climate_df: pd.DataFrame) -> np.ndarray:
        temp = climate_df['temperature'].values
        precip = climate_df['precipitation'].values

        # 温度响应：28°C 峰值
        temp_factor = np.exp(-0.5 * ((temp - 28) / 6) ** 2)

        # 降水响应
        precip_factor = 1 + 0.004 * np.minimum(precip, 250)

        return temp_factor * precip_factor

    def get_optimal_climate_range(self) -> dict:
        return {
            'temperature': (22, 34),
            'precipitation': (100, 400),
            'humidity': (65, 85),
        }


class CholeraFeatures(DiseaseFeatureEngineer):
    """霍乱特异性特征"""

    def compute_transmission_factor(self, climate_df: pd.DataFrame) -> np.ndarray:
        temp = climate_df['temperature'].values
        precip = climate_df['precipitation'].values

        # 温度响应
        temp_factor = np.where((temp >= 25) & (temp <= 35), 1.5, 0.8)

        # 洪水事件检测
        precip_7d = climate_df['precipitation'].rolling(7, min_periods=1).sum().fillna(0).values
        flood_factor = np.where(precip_7d > np.percentile(precip_7d, 90), 2.0, 1.0)

        return temp_factor * flood_factor

    def get_optimal_climate_range(self) -> dict:
        return {
            'temperature': (15, 40),
            'precipitation': (0, 500),
            'humidity': (50, 95),
        }


class ZikaFeatures(DiseaseFeatureEngineer):
    """寨卡病毒特征"""

    def compute_transmission_factor(self, climate_df: pd.DataFrame) -> np.ndarray:
        dengue_model = DengueFeatures()
        base_factor = dengue_model.compute_transmission_factor(climate_df)
        return base_factor * 0.7

    def get_optimal_climate_range(self) -> dict:
        return {
            'temperature': (22, 34),
            'precipitation': (100, 350),
            'humidity': (65, 85),
        }


class DomainFeatureManager:
    """管理所有疾病的特征工程"""

    def __init__(self):
        se

# ============================================
# 第 2 步：创建增强版 NLP 检测器模块 - Part 2
# ============================================
print("\n" + "="*70)
print("创建增强版 NLP 检测器模块")
print("="*70)

# 定义要写入文件的代码内容
nlp_enhanced_code = '''from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import numpy as np
import joblib

class EnhancedOutbreakDetector:
    def __init__(self):
        self.vectorizer = TfidfVectorizer(max_features=1000, ngram_range=(1, 3))
        self.outbreak_classifier = LogisticRegression(max_iter=2000, random_state=42)
        self.disease_classifier = LogisticRegression(max_iter=2000, random_state=42)
        self.disease_labels = ['malaria', 'dengue', 'cholera', 'zika']

    def train(self, texts: list, outbreak_labels: list, disease_labels: list):
        X = self.vectorizer.fit_transform(texts)

        # 训练爆发分类器
        self.outbreak_classifier.fit(X, outbreak_labels)

        # 训练疾病分类器
        outbreak_indices = [i for i, label in enumerate(outbreak_labels) if label == 1]
        if len(outbreak_indices) > 0:
            X_outbreak = X[outbreak_indices]
            y_disease = [disease_labels[i] for i in outbreak_indices]
            y_disease_encoded = [self.disease_labels.index(d) if d in self.disease_labels else 0
                                  for d in y_disease]
            self.disease_classifier.fit(X_outbreak, y_disease_encoded)

    def predict(self, texts: list) -> list:
        X = self.vectorizer.transform(texts)
        outbreak_pred = self.outbreak_classifier.predict(X)
        outbreak_proba = self.outbreak_classifier.predict_proba(X)[:, 1]

        results = []
        for i, text in enumerate(texts):
            disease = 'none'
            if outbreak_pred[i] == 1:
                disease_idx = self.disease_classifier.predict(X[i])[0]
                disease = self.disease_labels[int(disease_idx)]

            severity = 'high' if outbreak_proba[i] > 0.7 else 'medium' if outbreak_proba[i] > 0.4 else 'low'

            results.append({
                'text': text,
                'is_outbreak': bool(outbreak_pred[i]),
                'confidence': float(outbreak_proba[i]),
                'disease': disease,
                'severity': severity,
                'urgency_score': float(outbreak_proba[i])
            })
        return results

    def save(self, path: str):
        joblib.dump({
            'vectorizer': self.vectorizer,
            'outbreak_classifier': self.outbreak_classifier,
            'disease_classifier': self.disease_classifier,
            'disease_labels': self.disease_labels
        }, path)

    @classmethod
    def load(cls, path: str):
        data = joblib.load(path)
        instance = cls()
        instance.vectorizer = data['vectorizer']
        instance.outbreak_classifier = data['outbreak_classifier']
        instance.disease_classifier = data['disease_classifier']
        instance.disease_labels = data['disease_labels']
        return instance

def generate_expanded_training_set():
    malaria_outbreak = [
        'Malaria cases surge in rural districts following heavy monsoon rains',
        'WHO reports alarming increase in malaria infections across East Africa',
        'Emergency declared as malaria outbreak spreads rapidly',
        'Hospitals overwhelmed by malaria patients after flooding',
        'Record malaria deaths reported in past month',
        'Severe malaria cases strain health facilities',
        'Malaria epidemic declared after seasonal rains',
        'Anopheles mosquito population explodes creating risk',
        'Mass malaria treatment campaign launched',
        'Malaria transmission spikes with warm weather',
    ] * 2

    dengue_outbreak = [
        'Dengue fever outbreak grips capital as cases triple',
        'Aedes mosquito breeding explodes after urban flooding',
        'Hospitals run out of platelets amid dengue surge',
        'Cities declare dengue emergency with record infections',
        'Schools closed as dengue outbreak spreads',
        'Dengue death toll rises in monsoon regions',
        'Fumigation drive launched as dengue cases spike',
        'ICU beds full with severe dengue patients',
        'Dengue outbreak strains healthcare systems',
        'Climate patterns fuel worst dengue season',
    ] * 2

    cholera_outbreak = [
        'Cholera epidemic spreads through flood-devastated regions',
        'Water contamination triggers massive cholera outbreak',
        'Cholera cases surge after cyclone damages infrastructure',
        'Emergency rehydration stations set up for cholera',
        'Cholera deaths mount lacking clean water access',
        'Refugees face cholera crisis in overcrowded camps',
        'Vibrio cholerae detected in water sources after floods',
        'Cholera outbreak declared as diarrhea cases skyrocket',
        'International aid rushed to combat cholera epidemic',
        'Cholera transmission accelerates in coastal areas',
    ] * 2

    zika_outbreak = [
        'Zika virus cases rise as Aedes mosquitoes spread',
        'Pregnant women warned as Zika outbreak intensifies',
        'Zika-linked microcephaly cases reported in outbreak',
        'Travel warnings issued due to Zika outbreak',
        'Zika virus detected in previously disease-free areas',
        'Emergency Zika response teams deployed',
        'Zika outbreak prompts mosquito control efforts',
        'Birth defects rise as Zika outbreak continues',
        'International concern over expanding Zika outbreak',
        'Zika cases surge following warm winter season',
    ] * 2

    normal = [
        'New malaria vaccine shows promising trial results',
        'Community workers distribute insecticide-treated nets',
        'Annual malaria prevention campaign begins',
        'Research team discovers malaria prevention approach',
        'Government invests in malaria control infrastructure',
        'Routine malaria testing available at health centers',
        'Malaria awareness program educates villagers',
        'New diagnostic tool improves malaria detection',
        'Seasonal prevention measures rolled out',
        'Health ministry reports stable case numbers',
        'Farmers market opens with fresh produce',
        'New school construction completed in rural area',
        'Local team wins regional sports championship',
        'Cultural festival celebrates traditional arts',
        'Road improvement project enhances connectivity',
    ] * 3

    all_texts = malaria_outbreak + dengue_outbreak + cholera_outbreak + zika_outbreak + normal
    outbreak_labels = [1] * (len(malaria_outbreak) + len(dengue_outbreak) +
                             len(cholera_outbreak) + len(zika_outbreak)) + [0] * len(normal)
    disease_labels = (['malaria'] * len(malaria_outbreak) +
                     ['dengue'] * len(dengue_outbreak) +
                     ['cholera'] * len(cholera_outbreak) +
                     ['zika'] * len(zika_outbreak) +
                     ['none'] * len(normal))

    return all_texts, outbreak_labels, disease_labels
'''

# 确保目录存在
import os
os.makedirs('models', exist_ok=True)

# 写入文件
with open('models/nlp_detector_enhanced.py', 'w', encoding='utf-8') as f:
    f.write(nlp_enhanced_code)

print("✅ models/nlp_detector_enhanced.py 已创建")
print("\n✅ 所有融合模块文件创建完成")

# ============================================
# 第 3 步：获取真实数据
# ============================================
print("\n" + "="*70)
print("  🌐 获取真实数据（NASA/WHO/GDELT）")
print("="*70)

import pandas as pd
import os

# 首先检查当前目录
print(f"\n当前工作目录: {os.getcwd()}")
print(f"\n目录结构:")
!ls -la

# 检查 data 文件夹
if os.path.exists('data'):
    print(f"\ndata/ 文件夹内容:")
    !ls -la data/
else:
    print("\n⚠️  data/ 文件夹不存在，创建中...")
    !mkdir -p data

# 检查 fetch_real_data.py 是否存在
fetch_script_path = 'data/fetch_real_data.py'
if os.path.exists(fetch_script_path):
    print(f"\n✅ 找到 {fetch_script_path}")
    print(f"文件大小: {os.path.getsize(fetch_script_path)} 字节")

    # 运行数据获取脚本
    print("\n开始运行数据获取脚本...")
    !python data/fetch_real_data.py

elif os.path.exists('fetch_real_data.py'):
    print(f"\n✅ 找到 fetch_real_data.py（在当前目录）")
    !python fetch_real_data.py

else:
    print(f"\n⚠️  未找到 fetch_real_data.py")
    print("尝试直接在 Python 中导入...")

    # 方案 B：直接导入并运行
    try:
        import sys
        sys.path.insert(0, 'data')
        import fetch_real_data
        print("✅ 成功导入 fetch_real_data 模块")

        # 如果模块有 main 函数，调用它
        if hasattr(fetch_real_data, 'main'):
            fetch_real_data.main()
        elif hasattr(fetch_real_data, 'fetch_all_data'):
            fetch_real_data.fetch_all_data()
        else:
            print("⚠️  模块没有 main() 或 fetch_all_data() 函数")
            print("可用的函数:", dir(fetch_real_data))

    except ImportError as e:
        print(f"❌ 导入失败: {e}")
        print("\n将使用合成数据作为后备方案...")

# 检查数据是否生成
print("\n" + "="*70)
print("检查数据文件")
print("="*70)

data_files = [
    'data/real_data.csv',
    'real_data.csv',
    'data/climate_data.csv',
    'data/disease_data.csv'
]

df = None
for data_file in data_files:
    if os.path.exists(data_file):
        print(f"\n✅ 找到数据文件: {data_file}")
        try:
            df = pd.read_csv(data_file)
            print(f"   数据加载成功: {len(df)} 行 × {len(df.columns)} 列")
            print(f"   列名: {df.columns.tolist()}")
            print(f"\n数据预览:")
            print(df.head())
            break
        except Exception as e:
            print(f"   ❌ 加载失败: {e}")

if df is None:
    print("\n⚠️  未找到真实数据文件")
    print("生成合成数据作为后备...")

    # 生成简单的合成数据
    import numpy as np
    from datetime import datetime, timedelta

    n_samples = 1000
    start_date = datetime(2020, 1, 1)

    dates = [start_date + timedelta(days=i) for i in range(n_samples)]
    diseases = np.random.choice(['malaria', 'dengue', 'cholera', 'zika'], n_samples)

    df = pd.DataFrame({
        'date': dates,
        'disease': diseases,
        'temperature': np.random.normal(27, 5, n_samples),
        'precipitation': np.random.gamma(2, 50, n_samples),
        'humidity': np.random.normal(75, 10, n_samples),
        'cases': np.random.poisson(100, n_samples),
        'outbreak': np.random.choice([0, 1], n_samples, p=[0.8, 0.2])
    })

    df.to_csv('data/real_data.csv', index=False)
    print(f"\n✅ 合成数据已生成: {len(df)} 行")
    print(f"   保存位置: data/real_data.csv")
    print(f"\n数据预览:")
    print(df.head())

print("\n✅ 数据准备完成")

# ============================================
# 第 4 步：数据预处理与特征工程
# ============================================
print("\n" + "="*70)
print("  🔧 数据预处理与领域特征工程")
print("="*70)

# 导入新创建的模块
import sys
sys.path.insert(0, 'models')
from disease_domain_features import DomainFeatureManager

# 初始化特征管理器
feature_manager = DomainFeatureManager()

# 为每种疾病应用特征工程
if df is not None and 'disease' in df.columns:
    diseases = df['disease'].unique()
    print(f"\n检测到疾病类型: {diseases}")

    enhanced_dfs = []
    for disease in diseases:
        if disease in ['malaria', 'dengue', 'cholera', 'zika']:
            print(f"\n处理 {disease} 数据...")
            disease_df = df[df['disease'] == disease].copy()

            # 应用领域特征工程
            climate_cols = ['temperature', 'precipitation']
            if 'humidity' in disease_df.columns:
                climate_cols.append('humidity')

            climate_df = disease_df[climate_cols].copy()
            enhanced = feature_manager.engineer_features(climate_df, disease)

            # 合并回原数据
            for col in enhanced.columns:
                if col not in disease_df.columns:
                    disease_df[col] = enhanced[col].values

            enhanced_dfs.append(disease_df)
            print(f"  ✅ {disease} 特征增强完成，新增 {len(enhanced.columns) - len(climate_cols)} 个特征")

    # 合并所有数据
    df_enhanced = pd.concat(enhanced_dfs, ignore_index=True)
    df_enhanced.to_csv('data/enhanced_data.csv', index=False)
    print(f"\n✅ 增强数据已保存: data/enhanced_data.csv")
else:
    print("\n⚠️  跳过特征工程（数据格式问题）")
    df_enhanced = df

# ============================================
# 第 5 步：训练增强版疾病预测模型
# ============================================
print("\n" + "="*70)
print("  🤖 训练疾病特异性预测模型")
print("="*70)

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score
import joblib

class EnhancedDiseasePredictor:
    def __init__(self, disease: str):
        self.disease = disease
        self.rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
        self.gb_model = GradientBoostingClassifier(n_estimators=100, max_depth=5, random_state=42)
        self.lr_model = LogisticRegression(max_iter=1000, random_state=42)
        self.weights = {'rf': 0.45, 'gb': 0.45, 'lr': 0.10}
        self.feature_names = None

    def train(self, X, y):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

        print(f"  训练 {self.disease} 模型...")
        self.rf_model.fit(X_train, y_train)
        self.gb_model.fit(X_train, y_train)
        self.lr_model.fit(X_train, y_train)

        # 评估
        y_pred, y_pred_proba = self.predict(X_test)
        print(f"\n  {self.disease.upper()} 性能:")
        print(classification_report(y_test, y_pred, target_names=['正常', '爆发']))
        print(f"  ROC-AUC: {roc_auc_score(y_test, y_pred_proba):.3f}")

    def predict(self, X):
        rf_pred = self.rf_model.predict_proba(X)[:, 1]
        gb_pred = self.gb_model.predict_proba(X)[:, 1]
        lr_pred = self.lr_model.predict_proba(X)[:, 1]
        ensemble_pred = self.weights['rf'] * rf_pred + self.weights['gb'] * gb_pred + self.weights['lr'] * lr_pred
        return (ensemble_pred > 0.5).astype(int), ensemble_pred

    def save(self, path: str):
        joblib.dump({
            'disease': self.disease,
            'rf_model': self.rf_model,
            'gb_model': self.gb_model,
            'lr_model': self.lr_model,
            'weights': self.weights,
            'feature_names': self.feature_names
        }, path)

    @classmethod
    def load(cls, path: str):
        data = joblib.load(path)
        instance = cls(data['disease'])
        instance.rf_model = data['rf_model']
        instance.gb_model = data['gb_model']
        instance.lr_model = data['lr_model']
        instance.weights = data['weights']
        instance.feature_names = data['feature_names']
        return instance

# 训练所有疾病模型
if df_enhanced is not None and 'outbreak' in df_enhanced.columns:
    for disease in ['malaria', 'dengue', 'cholera', 'zika']:
        disease_data = df_enhanced[df_enhanced['disease'] == disease]

        if len(disease_data) < 50:
            print(f"\n⚠️  {disease} 数据不足，跳过")
            continue

        print(f"\n{'='*60}")
        print(f"训练 {disease.upper()} 模型")
        print('='*60)

        # ✅ 只选择基础特征 + 当前疾病的特征
        feature_cols = ['temperature', 'precipitation', 'humidity']
        disease_specific_cols = [col for col in disease_data.columns
                                if col.startswith(f'{disease}_')]
        feature_cols.extend(disease_specific_cols)

        # 打印特征信息
        print(f"  基础特征: {feature_cols[:3]}")
        print(f"  {disease} 特定特征: {disease_specific_cols}")
        print(f"  总特征数: {len(feature_cols)}")

        X = disease_data[feature_cols].fillna(0).values
        y = disease_data['outbreak'].values

        # 训练
        model = EnhancedDiseasePredictor(disease)
        model.feature_names = feature_cols  # 只保存 7 个特征（3基础 + 4疾病特定）
        model.train(X, y)

        # 保存
        model.save(f'saved_models/{disease}_predictor_enhanced.pkl')
        print(f"\n✅ {disease} 模型已保存")
        print(f"   模型特征数: {len(model.feature_names)}")
else:
    print("\n⚠️  跳过疾病模型训练（数据不可用）")

# ============================================
# 第 6 步：训练增强版 NLP 检测器
# ============================================
print("\n" + "="*70)
print("  📰 训练增强版 NLP 爆发检测器")
print("="*70)

from nlp_detector_enhanced import EnhancedOutbreakDetector, generate_expanded_training_set

# 生成训练集
texts, outbreak_labels, disease_labels = generate_expanded_training_set()
print(f"\nNLP 训练集: {len(texts)} 样本")
print(f"  爆发样本: {sum(outbreak_labels)}")
print(f"  正常样本: {len(texts) - sum(outbreak_labels)}")

# 训练
nlp_model = EnhancedOutbreakDetector()
nlp_model.train(texts, outbreak_labels, disease_labels)
nlp_model.save('saved_models/nlp_detector_enhanced.pkl')

print("\n✅ NLP 模型训练完成")

# 测试
test_headlines = [
    'Massive dengue outbreak in Southeast Asia after floods',
    'Malaria cases surge 40% in East Africa highlands',
    'Cholera spreads through flood-damaged water systems',
    'Local farmers celebrate successful harvest season',
    'Zika emergency declared in Caribbean islands',
]

print("\n" + "="*70)
print("NLP 检测测试")
print("="*70)
results = nlp_model.predict(test_headlines)
for r in results:
    emoji = '🔴 OUTBREAK' if r['is_outbreak'] else '🟢 Normal'
    print(f"{emoji} | {r['disease']:8s} | conf={r['confidence']:.2f} | {r['severity']}")
    print(f"   \"{r['text'][:60]}...\"\n")

# ============================================
# 第 7 步：训练气候预测器
# ============================================
print("\n" + "="*70)
print("  🌡 训练气候预测器")
print("="*70)

# 如果有 train_real.py，运行它来训练气候模型
import os
if os.path.exists('train_real.py'):
    print("使用 train_real.py 训练气候模型...")
    !python train_real.py
else:
    print()
    !python train.py

print("\n✅ 气候预测器训练完成")

# ============================================
# 第 8 步：创建融合集成引擎
# ============================================
print("\n" + "="*70)
print("  🎯 创建融合风险评估引擎")
print("="*70)

import numpy as np

class FusionRiskEngine:
    """融合风险评估引擎"""

    def __init__(self, disease_model, nlp_model):
        self.disease_model = disease_model
        self.nlp_model = nlp_model
        self.base_weights = {'climate': 0.35, 'disease': 0.50, 'nlp': 0.15}

    def assess_risk(self, climate_df, news_texts, disease='malaria'):
        # ✅ 修改：确保 climate_df 已经是增强后的特征
        # 如果传入的是原始数据，先进行特征工程
        if 'transmission_factor' not in climate_df.columns:
            from disease_domain_features import DomainFeatureManager
            manager = DomainFeatureManager()
            enhanced = manager.engineer_features(climate_df, disease)
        else:
            enhanced = climate_df

        # 2. 疾病模型预测
        # ✅ 使用模型保存的特征列表
        if hasattr(self.disease_model, 'feature_names'):
            feature_cols = self.disease_model.feature_names
        else:
            feature_cols = [col for col in enhanced.columns
                           if not col.startswith('date')]

        X = enhanced[feature_cols].fillna(0).values[-1:]  # 最新一行
        _, disease_prob = self.disease_model.predict(X)
        disease_risk = disease_prob[0] * 100

        # 3. NLP 分析
        nlp_results = self.nlp_model.predict(news_texts)
        relevant = [r for r in nlp_results if r['is_outbreak'] and r['disease'] == disease]
        nlp_risk = np.mean([r['confidence'] for r in relevant]) * 100 if relevant else 0

        # 4. 气候风险（简化计算）
        temp = enhanced['temperature'].iloc[-1] if 'temperature' in enhanced.columns else climate_df['temperature'].iloc[-1]
        precip = enhanced['precipitation'].iloc[-1] if 'precipitation' in enhanced.columns else climate_df['precipitation'].iloc[-1]

        from disease_domain_features import DomainFeatureManager
        manager = DomainFeatureManager()
        optimal = manager.disease_models[disease].get_optimal_climate_range()

        temp_in_range = optimal['temperature'][0] <= temp <= optimal['temperature'][1]
        precip_in_range = optimal['precipitation'][0] <= precip <= optimal['precipitation'][1]
        climate_risk = 75 if (temp_in_range and precip_in_range) else 40

        # 5. 加权计算
        final_score = (
            self.base_weights['climate'] * climate_risk +
            self.base_weights['disease'] * disease_risk +
            self.base_weights['nlp'] * nlp_risk
        )

        risk_level = 'critical' if final_score >= 75 else \
                    'high' if final_score >= 60 else \
                    'medium' if final_score >= 40 else 'low'

        return {
            'risk_score': round(final_score, 1),
            'risk_level': risk_level,
            'outbreak_probability': round(disease_prob[0], 3),
            'component_scores': {
                'climate_risk': round(climate_risk, 1),
                'disease_risk': round(disease_risk, 1),
                'nlp_risk': round(nlp_risk, 1)
            },
            'nlp_signals': nlp_results
        }

# ============================================
# 第 9 步：端到端测试
# ============================================
print("\n" + "="*70)
print("  🧪 端到端测试")
print("="*70)

import pandas as pd

# 加载模型
try:
    malaria_model = EnhancedDiseasePredictor.load('saved_models/malaria_predictor_enhanced.pkl')
    nlp_model = EnhancedOutbreakDetector.load('saved_models/nlp_detector_enhanced.pkl')

    # 创建引擎
    engine = FusionRiskEngine(malaria_model, nlp_model)

    # 测试数据
    test_climate = pd.DataFrame({
        'temperature': [26, 27, 28, 27, 26, 25, 24, 25, 26, 27],
        'precipitation': [120, 150, 180, 200, 180, 160, 140, 130, 150, 170],
        'humidity': [75, 78, 80, 82, 80, 78, 76, 77, 79, 81],
    })

    # ✅ 关键修改：应用领域特征工程
    from disease_domain_features import DomainFeatureManager
    feature_manager = DomainFeatureManager()
    test_climate_enhanced = feature_manager.engineer_features(test_climate, 'malaria')

    print(f"\n✅ 特征工程完成:")
    print(f"   原始特征: {test_climate.shape[1]} 个")
    print(f"   增强特征: {test_climate_enhanced.shape[1]} 个")
    print(f"   特征列表: {test_climate_enhanced.columns.tolist()}")

    test_news = [
        'Malaria outbreak spreads in rural areas after heavy rains',
        'WHO reports increased malaria transmission in East Africa',
        'Emergency malaria response teams deployed',
    ]

    # 评估 - 使用增强后的数据
    result = engine.assess_risk(test_climate_enhanced, test_news, disease='malaria')

    # 打印结果
    print("\n" + "="*70)
    print("  融合风险评估结果 - MALARIA")
    print("="*70)
    print(f"  风险分数:      {result['risk_score']}/100")
    print(f"  风险等级:      {result['risk_level'].upper()}")
    print(f"  爆发概率:      {result['outbreak_probability']*100:.1f}%")
    print(f"\n  组件分数:")
    for comp, score in result['component_scores'].items():
        print(f"    {comp:20s} {score:>6.1f}/100")
    print("="*70)

    print("\n✅ 端到端测试成功！")

except Exception as e:
    print(f"\n⚠️  测试失败: {str(e)}")
    print("\n详细错误信息:")
    import traceback
    traceback.print_exc()

    # 检查模型的特征要求
    if 'malaria_model' in locals():
        print(f"\n模型期望的特征数量: {len(malaria_model.feature_names)}")
        print(f"模型期望的特征名称: {malaria_model.feature_names}")

